import { createApi } from "@reduxjs/toolkit/query/react";
// Define our single API slice object

import { graphqlRequestBaseQuery } from "@rtk-query/graphql-request-base-query";


const apiBaseQuery = graphqlRequestBaseQuery({
    url: "https://karyhealthproducts.com/graphql",
    credentials: 'include',

    prepareHeaders: (headers, { getState }) => {
      headers.set("Content-Type", "application/json");
      const token = getState().auth.token;
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }
      return headers;
    },
    
})
const apiBaseQueryWithReauth = async (args, api, extraOptions) => {
  let result = await apiBaseQuery(args, api, extraOptions);

  if (result?.error?.orginalStatus === 403 || result?.error?.orginalStatus === 401) {
    console.log('sending refresh token')
    const refreshResult = await apiBaseQuery(api.refreshToken(api.getState().auth.refreshToken), api, extraOptions);

    console.log(refreshResult);
    if (refreshResult?.data) {
      const user = api.getState().auth
      api.dispatch(api.setCredentials({ ...refreshResult.data, user }))
      result = await apiBaseQuery(args, api, extraOptions);
    } else {
      api.dispatch(api.logout());
    }
  } 
  return result;
  }

export const apiSlice = createApi({
  // reducerPath: "apiSlice",
  baseQuery: apiBaseQueryWithReauth,
  endpoints: builder => ({})
 
});

// useRegisterUserMutation, useCreateOrderMutation

export const counties = [
  {
    name: "Baringo",
    capital: "Kabarnet",
    code: 30,
    sub_counties: [
      "Baringo central",
      "Baringo north",
      "Baringo south",
      "Eldama ravine",
      "Mogotio",
      "Tiaty",
    ],
  },
  {
    name: "Bomet",
    capital: "Bomet",
    code: 36,
    sub_counties: [
      "Bomet central",
      "Bomet east",
      "Chepalungu",
      "Konoin",
      "Sotik",
    ],
  },
  {
    name: "Bungoma",
    capital: "Bungoma",
    code: 39,
    sub_counties: [
      "Bumula",
      "Kabuchai",
      "Kanduyi",
      "Kimilil",
      "Mt Elgon",
      "Sirisia",
      "Tongaren",
      "Webuye east",
      "Webuye west",
    ],
  },
  {
    name: "Busia",
    capital: "Busia",
    code: 40,
    sub_counties: [
      "Budalangi",
      "Butula",
      "Funyula",
      "Nambele",
      "Teso North",
      "Teso South",
    ],
  },
  {
    name: "Elgeyo-Marakwet",
    capital: "Iten",
    code: 28,
    sub_counties: [
      "Keiyo north",
      "Keiyo south",
      "Marakwet east",
      "Marakwet west",
    ],
  },
  {
    name: "Embu",
    capital: "Embu",
    code: 14,
    sub_counties: ["Manyatta", "Mbeere north", "Mbeere south", "Runyenjes"],
  },
  {
    name: "Garissa",
    capital: "Garissa",
    code: 7,
    sub_counties: [
      "Daadab",
      "Fafi",
      "Garissa",
      "Hulugho",
      "Ijara",
      "Lagdera balambala",
    ],
  },
  {
    name: "Homa Bay",
    capital: "Homa Bay",
    code: 43,
    sub_counties: [
      "Homabay town",
      "Kabondo",
      "Karachwonyo",
      "Kasipul",
      "Mbita",
      "Ndhiwa",
      "Rangwe",
      "Suba",
    ],
  },
  {
    name: "Isiolo",
    capital: "Isiolo",
    code: 11,
    sub_counties: ["Isiolo", "Garba tula", "Merit"],
  },
  {
    name: "Kajiado",
    code: 34,
    sub_counties: [
      "Isinya.",
      "Kajiado Central.",
      "Kajiado North.",
      "Loitokitok.",
      "Mashuuru.",
    ],
  },
  {
    name: "Kakamega",
    capital: "Kakamega",
    code: 37,
    sub_counties: [
      "Butere",
      "Kakamega central",
      "Kakamega east",
      "Kakamega north",
      "Kakamega south",
      "Khwisero",
      "Lugari",
      "Lukuyani",
      "Lurambi",
      "Matete",
      "Mumias",
      "Mutungu",
      "Navakholo",
    ],
  },
  {
    name: "Kericho",
    capital: "Kericho",
    code: 35,
    sub_counties: [
      "Ainamoi",
      "Belgut",
      "Bureti",
      "Kipkelion east",
      "Kipkelion west",
      "Soin sigowet",
    ],
  },
  {
    name: "Kiambu",
    capital: "Kiambu",
    code: 22,
    sub_counties: [
      "Gatundu north",
      "Gatundu south",
      "Githunguri",
      "Juja",
      "Kabete",
      "Kiambaa",
      "Kiambu",
      "Kikuyu",
      "Limuru",
      "Ruiru",
      "Thika town",
      "lari",
    ],
  },
  {
    name: "Kilifi",
    capital: "Kilifi",
    code: 3,
    sub_counties: [
      "Genzw",
      "Kaloleni",
      "Kilifi north",
      "Kilifi south",
      "Magarini",
      "Malindi",
      "Rabai",
    ],
  },
  {
    name: "Kirinyaga",
    capital: "Kerugoya/Kutus",
    code: 20,
    sub_counties: [
      "Kirinyaga central",
      "Kirinyaga east",
      "Kirinyaga west",
      "Mwea east",
      "Mwea west",
    ],
  },
  {
    name: "Kisii",
    capital: "Kisii",
    code: 45,
    sub_counties: [],
  },
  {
    name: "Kisumu",
    capital: "Kisumu",
    code: 42,
    sub_counties: [
      "Kisumu central",
      "Kisumu east ",
      "Kisumu west",
      "Mohoroni",
      "Nyakach",
      "Nyando",
      "Seme",
    ],
  },
  {
    name: "Kitui",
    capital: "Kitui",
    code: 15,
    sub_counties: [
      "Ikutha",
      "Katulani",
      "Kisasi",
      "Kitui central",
      "Kitui west ",
      "Lower yatta",
      "Matiyani",
      "Migwani",
      "Mutitu",
      "Mutomo",
      "Muumonikyusu",
      "Mwingi central",
      "Mwingi east",
      "Nzambani",
      "Tseikuru",
    ],
  },
  {
    name: "Kwale",
    capital: "Kwale",
    code: 2,
    sub_counties: ["Kinango", "Lungalunga", "Msambweni", "Mutuga"],
  },
  {
    name: "Laikipia",
    capital: "Rumuruti",
    code: 31,
    sub_counties: [
      "Laikipia central",
      "Laikipia east",
      "Laikipia north",
      "Laikipia west ",
      "Nyahururu",
    ],
  },
  {
    name: "Lamu",
    capital: "Lamu",
    code: 5,
    sub_counties: ["Lamu East", "Lamu West"],
  },
  {
    name: "Machakos",
    capital: "Machakos",
    code: 16,
    sub_counties: [
      "Kathiani",
      "Machakos town",
      "Masinga",
      "Matungulu",
      "Mavoko",
      "Mwala",
      "Yatta",
    ],
  },
  {
    name: "Makueni",
    capital: "Wote",
    code: 17,
    sub_counties: [
      "Kaiti",
      "Kibwei west",
      "Kibwezi east",
      "Kilome",
      "Makueni",
      "Mbooni",
    ],
  },
  {
    name: "Mandera",
    capital: "Mandera",
    code: 9,
    sub_counties: [
      "Banissa",
      "Lafey",
      "Mandera East",
      "Mandera North",
      "Mandera South",
      "Mandera West",
    ],
  },
  {
    name: "Marsabit",
    capital: "Marsabit",
    code: 10,
    sub_counties: ["Laisamis", "Moyale", "North hor", "Saku"],
  },
  {
    name: "Meru",
    capital: "Meru",
    code: 12,
    sub_counties: [
      "Buuri",
      "Igembe central",
      "Igembe north",
      "Igembe south",
      "Imenti central",
      "Imenti north",
      "Imenti south",
      "Tigania east",
      "Tigania west",
    ],
  },
  {
    name: "Migori",
    capital: "Migori",
    code: 44,
    sub_counties: [
      "Awendo",
      "Kuria east",
      "Kuria west",
      "Mabera",
      "Ntimaru",
      "Rongo",
      "Suna east",
      "Suna west",
      "Uriri",
    ],
  },
  {
    name: "Mombasa",
    capital: "Mombasa City",
    code: 1,
    sub_counties: ["Changamwe", "Jomvu", "Kisauni", "Likoni", "Mvita", "Nyali"],
  },
  {
    name: "Murang'a",
    capital: "Murang'a",
    code: 21,
    sub_counties: [
      "Gatanga",
      "Kahuro",
      "Kandara",
      "Kangema",
      "Kigumo",
      "Kiharu",
      "Mathioya",
      "Murang’a south",
    ],
  },
  {
    name: "Nairobi",
    capital: "Nairobi City",
    code: 47,
    sub_counties: [
      "Dagoretti North Sub County",
      "Dagoretti South Sub County ",
      "Embakasi Central Sub Count",
      "Embakasi East Sub County",
      "Embakasi North Sub County ",
      "Embakasi South Sub County",
      "Embakasi West Sub County",
      "Kamukunji Sub County",
      "Kasarani Sub County ",
      "Kibra Sub County ",
      "Lang'ata Sub County ",
      "Makadara Sub County",
      "Mathare Sub County ",
      "Roysambu Sub County ",
      "Ruaraka Sub County ",
      "Starehe Sub County ",
      "Westlands Sub County ",
    ],
  },
  {
    name: "Nakuru",
    capital: "Nakuru",
    code: 32,
    sub_counties: [
      "Bahati",
      "Gilgil",
      "Kuresoi north",
      "Kuresoi south",
      "Molo",
      "Naivasha",
      "Nakuru town east",
      "Nakuru town west",
      "Njoro",
      "Rongai",
      "Subukia",
    ],
  },
  {
    name: "Nandi",
    capital: "Kapsabet",
    code: 29,
    sub_counties: [
      "Aldai",
      "Chesumei",
      "Emgwen",
      "Mosop",
      "Namdi hills",
      "Tindiret",
    ],
  },
  {
    name: "Narok",
    capital: "Narok",
    code: 33,
    sub_counties: [
      "Narok east",
      "Narok north",
      "Narok south",
      "Narok west",
      "Transmara east",
      "Transmara west",
    ],
  },
  {
    name: "Nyamira",
    capital: "Nyamira",
    code: 46,
    sub_counties: [
      "Borabu",
      "Manga",
      "Masaba north",
      "Nyamira north",
      "Nyamira south",
    ],
  },
  {
    name: "Nyandarua",
    capital: "Ol Kalou",
    code: 18,
    sub_counties: [
      "Kinangop",
      "Kipipiri",
      "Ndaragwa",
      "Ol Kalou",
      "Ol joro orok",
    ],
  },
  {
    name: "Nyeri",
    capital: "Nyeri",
    code: 19,
    sub_counties: [
      "Kieni east",
      "Kieni west",
      "Mathira east",
      "Mathira west",
      "Mkurweni",
      "Nyeri town",
      "Othaya",
      "Tetu",
    ],
  },
  {
    name: "Samburu",
    capital: "Maralal",
    code: 25,
    sub_counties: ["Samburu east", "Samburu north", "Samburu west"],
  },
  {
    name: "Siaya",
    capital: "Siaya",
    code: 41,
    sub_counties: [
      "Alego usonga",
      "Bondo",
      "Gem",
      "Rarieda",
      "Ugenya",
      "Unguja",
    ],
  },
  {
    name: "Taita-Taveta",
    capital: "Voi",
    code: 6,
    sub_counties: ["Mwatate", "Taveta", "Voi", "Wundanyi"],
  },
  {
    name: "Tana River",
    capital: "Hola",
    code: 4,
    sub_counties: ["Bura", "Galole", "Garsen"],
  },
  {
    name: "Tharaka-Nithi",
    capital: "Chuka",
    code: 13,
    sub_counties: [
      "Chuka",
      "Igambangobe",
      "Maara",
      "Muthambi",
      "Tharak north",
      "Tharaka south",
    ],
  },
  {
    name: "Trans-Nzoia",
    capital: "Kitale",
    code: 26,
    sub_counties: ["Cherangany", "Endebess", "Kiminini", "Kwanza", "Saboti"],
  },
  {
    name: "Turkana",
    capital: "Lodwar",
    code: 23,
    sub_counties: [
      "Loima",
      "Turkana central",
      "Turkana east",
      "Turkana north",
      "Turkana south",
    ],
  },
  {
    name: "Uasin Gishu",
    capital: "Eldoret",
    code: 27,
    sub_counties: ["Ainabkoi", "Kapseret", "Kesses", "Moiben", "Soy", "Turbo"],
  },
  {
    name: "Vihiga",
    capital: "Vihiga",
    code: 38,
    sub_counties: ["Emuhaya", "Hamisi", "Luanda", "Sabatia", "vihiga"],
  },
  {
    name: "Wajir",
    capital: "Wajir",
    code: 8,
    sub_counties: [
      "Eldas",
      "Tarbaj",
      "Wajir East",
      "Wajir North",
      "Wajir South",
      "Wajir West",
    ],
  },
  {
    name: "West Pokot",
    capital: "Kapenguria",
    code: 24,
    sub_counties: ["Central Pokot", "North Pokot", "Pokot South", "West Pokot"],
  },
];
export const prices = {
  currency_symbol: "KSh",
  currency_decimal_separator: ".",
  currency_thousand_separator: ",",
  currency_prefix: "KSh ",
  currency_suffix: "",
};
export const featured = [
  {
    id: 1849,
    name: "Long Sleeve Tee",
    parent: 0,
    type: "simple",
    variation: "",
    permalink: "http://localhost/wordpress/product/long-sleeve-tee/",
    sku: "woo-long-sleeve-tee",
    short_description: "<p>This is a simple product.</p>",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>",
    on_sale: false,
    prices: {
      price: "2500",
      regular_price: "2500",
      sale_price: "2500",
      price_range: null,
      currency_code: "KES",
      currency_symbol: "KSh",
      currency_minor_unit: 2,
      currency_decimal_separator: ".",
      currency_thousand_separator: ",",
      currency_prefix: "KSh ",
      currency_suffix: "",
    },
    price_html:
      '<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">KSh</span>&nbsp;25.00</span>',
    average_rating: "0",
    review_count: 0,
    images: [
      {
        id: 1895,
        src: "http://localhost/wordpress/wp-content/uploads/2022/06/long-sleeve-tee-2.jpg",
        thumbnail:
          "http://localhost/wordpress/wp-content/uploads/2022/06/long-sleeve-tee-2-300x300.jpg",
        srcset:
          "http://localhost/wordpress/wp-content/uploads/2022/06/long-sleeve-tee-2.jpg 801w, http://localhost/wordpress/wp-content/uploads/2022/06/long-sleeve-tee-2-300x300.jpg 300w, http://localhost/wordpress/wp-content/uploads/2022/06/long-sleeve-tee-2-100x100.jpg 100w",
        sizes: "(max-width: 801px) 100vw, 801px",
        name: "long-sleeve-tee-2.jpg",
        alt: "",
      },
    ],
    categories: [
      {
        id: 212,
        name: "Tshirts",
        slug: "tshirts",
        link: "http://localhost/wordpress/product-category/clothing/tshirts/",
      },
    ],
    tags: [],
    attributes: [],
    variations: [],
    has_options: false,
    is_purchasable: true,
    is_in_stock: true,
    is_on_backorder: false,
    low_stock_remaining: null,
    sold_individually: false,
    add_to_cart: {
      text: "Add to cart",
      description: "Add &ldquo;Long Sleeve Tee&rdquo; to your cart",
      url: "?add-to-cart=1849",
      minimum: 1,
      maximum: 9999,
      multiple_of: 1,
    },
  },
  {
    id: 1848,
    name: "Hoodie with Zipper",
    parent: 0,
    type: "simple",
    variation: "",
    permalink: "http://localhost/wordpress/product/hoodie-with-zipper/",
    sku: "woo-hoodie-with-zipper",
    short_description: "<p>This is a simple product.</p>",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>",
    on_sale: false,
    prices: {
      price: "4500",
      regular_price: "4500",
      sale_price: "4500",
      price_range: null,
      currency_code: "KES",
      currency_symbol: "KSh",
      currency_minor_unit: 2,
      currency_decimal_separator: ".",
      currency_thousand_separator: ",",
      currency_prefix: "KSh ",
      currency_suffix: "",
    },
    price_html:
      '<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">KSh</span>&nbsp;45.00</span>',
    average_rating: "0",
    review_count: 0,
    images: [
      {
        id: 1894,
        src: "http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2.jpg",
        thumbnail:
          "http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2-300x300.jpg",
        srcset:
          "http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2.jpg 800w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2-300x300.jpg 300w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2-100x100.jpg 100w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2-150x150.jpg 150w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2-768x768.jpg 768w",
        sizes: "(max-width: 800px) 100vw, 800px",
        name: "hoodie-with-zipper-2.jpg",
        alt: "",
      },
    ],
    categories: [
      {
        id: 213,
        name: "Hoodies",
        slug: "hoodies",
        link: "http://localhost/wordpress/product-category/clothing/hoodies/",
      },
    ],
    tags: [],
    attributes: [],
    variations: [],
    has_options: false,
    is_purchasable: true,
    is_in_stock: true,
    is_on_backorder: false,
    low_stock_remaining: null,
    sold_individually: false,
    add_to_cart: {
      text: "Add to cart",
      description: "Add &ldquo;Hoodie with Zipper&rdquo; to your cart",
      url: "?add-to-cart=1848",
      minimum: 1,
      maximum: 9999,
      multiple_of: 1,
    },
  },
  {
    id: 1847,
    name: "Hoodie with Pocket",
    parent: 0,
    type: "simple",
    variation: "",
    permalink: "http://localhost/wordpress/product/hoodie-with-pocket/",
    sku: "woo-hoodie-with-pocket",
    short_description: "<p>This is a simple product.</p>",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>",
    on_sale: true,
    prices: {
      price: "3500",
      regular_price: "4500",
      sale_price: "3500",
      price_range: null,
      currency_code: "KES",
      currency_symbol: "KSh",
      currency_minor_unit: 2,
      currency_decimal_separator: ".",
      currency_thousand_separator: ",",
      currency_prefix: "KSh ",
      currency_suffix: "",
    },
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">KSh</span>&nbsp;45.00</span></del> <ins><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">KSh</span>&nbsp;35.00</span></ins>',
    average_rating: "0",
    review_count: 0,
    images: [
      {
        id: 1893,
        src: "http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2.jpg",
        thumbnail:
          "http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2-300x300.jpg",
        srcset:
          "http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2.jpg 801w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2-300x300.jpg 300w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2-100x100.jpg 100w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2-150x150.jpg 150w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2-768x768.jpg 768w",
        sizes: "(max-width: 801px) 100vw, 801px",
        name: "hoodie-with-pocket-2.jpg",
        alt: "",
      },
    ],
    categories: [
      {
        id: 213,
        name: "Hoodies",
        slug: "hoodies",
        link: "http://localhost/wordpress/product-category/clothing/hoodies/",
      },
    ],
    tags: [],
    attributes: [],
    variations: [],
    has_options: false,
    is_purchasable: true,
    is_in_stock: true,
    is_on_backorder: false,
    low_stock_remaining: null,
    sold_individually: false,
    add_to_cart: {
      text: "Add to cart",
      description: "Add &ldquo;Hoodie with Pocket&rdquo; to your cart",
      url: "?add-to-cart=1847",
      minimum: 1,
      maximum: 9999,
      multiple_of: 1,
    },
  },
  {
    id: 1846,
    name: "Sunglasses",
    parent: 0,
    type: "simple",
    variation: "",
    permalink: "http://localhost/wordpress/product/sunglasses/",
    sku: "woo-sunglasses",
    short_description: "<p>This is a simple product.</p>",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>",
    on_sale: false,
    prices: {
      price: "9000",
      regular_price: "9000",
      sale_price: "9000",
      price_range: null,
      currency_code: "KES",
      currency_symbol: "KSh",
      currency_minor_unit: 2,
      currency_decimal_separator: ".",
      currency_thousand_separator: ",",
      currency_prefix: "KSh ",
      currency_suffix: "",
    },
    price_html:
      '<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">KSh</span>&nbsp;90.00</span>',
    average_rating: "0",
    review_count: 0,
    images: [
      {
        id: 1892,
        src: "http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2.jpg",
        thumbnail:
          "http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2-300x300.jpg",
        srcset:
          "http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2.jpg 801w, http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2-300x300.jpg 300w, http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2-100x100.jpg 100w, http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2-150x150.jpg 150w, http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2-768x768.jpg 768w",
        sizes: "(max-width: 801px) 100vw, 801px",
        name: "sunglasses-2.jpg",
        alt: "",
      },
    ],
    categories: [
      {
        id: 214,
        name: "Accessories",
        slug: "accessories",
        link: "http://localhost/wordpress/product-category/clothing/accessories/",
      },
    ],
    tags: [],
    attributes: [],
    variations: [],
    has_options: false,
    is_purchasable: true,
    is_in_stock: true,
    is_on_backorder: false,
    low_stock_remaining: null,
    sold_individually: false,
    add_to_cart: {
      text: "Add to cart",
      description: "Add &ldquo;Sunglasses&rdquo; to your cart",
      url: "?add-to-cart=1846",
      minimum: 1,
      maximum: 9999,
      multiple_of: 1,
    },
  },
];
