import {createApi, fetchBaseQuery} from "@reduxjs/toolkit/query/react"

export const productsApi = createApi({
  reducerPath: "productsApi",
  baseQuery: fetchBaseQuery({
    baseUrl: "http://karyhealthproducts.com/wp-json/wc/store/",
  }),
  endpoints: (builder) => ({
    getAllProducts: builder.query({
      query: () => `products`,
    }),
  }),
});
export const {useGetAllProductsQuery} = productsApi
export const featured = [
  {
    id: 1849,
    name: "Long Sleeve Tee",
    parent: 0,
    type: "simple",
    variation: "",
    permalink: "http://localhost/wordpress/product/long-sleeve-tee/",
    sku: "woo-long-sleeve-tee",
    short_description: "<p>This is a simple product.</p>",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>",
    on_sale: false,
    prices: {
      price: "2500",
      regular_price: "2500",
      sale_price: "2500",
      price_range: null,
      currency_code: "KES",
      currency_symbol: "KSh",
      currency_minor_unit: 2,
      currency_decimal_separator: ".",
      currency_thousand_separator: ",",
      currency_prefix: "KSh ",
      currency_suffix: "",
    },
    price_html:
      '<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">KSh</span>&nbsp;25.00</span>',
    average_rating: "0",
    review_count: 0,
    images: [
      {
        id: 1895,
        src: "http://localhost/wordpress/wp-content/uploads/2022/06/long-sleeve-tee-2.jpg",
        thumbnail:
          "http://localhost/wordpress/wp-content/uploads/2022/06/long-sleeve-tee-2-300x300.jpg",
        srcset:
          "http://localhost/wordpress/wp-content/uploads/2022/06/long-sleeve-tee-2.jpg 801w, http://localhost/wordpress/wp-content/uploads/2022/06/long-sleeve-tee-2-300x300.jpg 300w, http://localhost/wordpress/wp-content/uploads/2022/06/long-sleeve-tee-2-100x100.jpg 100w",
        sizes: "(max-width: 801px) 100vw, 801px",
        name: "long-sleeve-tee-2.jpg",
        alt: "",
      },
    ],
    categories: [
      {
        id: 212,
        name: "Tshirts",
        slug: "tshirts",
        link: "http://localhost/wordpress/product-category/clothing/tshirts/",
      },
    ],
    tags: [],
    attributes: [],
    variations: [],
    has_options: false,
    is_purchasable: true,
    is_in_stock: true,
    is_on_backorder: false,
    low_stock_remaining: null,
    sold_individually: false,
    add_to_cart: {
      text: "Add to cart",
      description: "Add &ldquo;Long Sleeve Tee&rdquo; to your cart",
      url: "?add-to-cart=1849",
      minimum: 1,
      maximum: 9999,
      multiple_of: 1,
    },
  },
  {
    id: 1848,
    name: "Hoodie with Zipper",
    parent: 0,
    type: "simple",
    variation: "",
    permalink: "http://localhost/wordpress/product/hoodie-with-zipper/",
    sku: "woo-hoodie-with-zipper",
    short_description: "<p>This is a simple product.</p>",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>",
    on_sale: false,
    prices: {
      price: "4500",
      regular_price: "4500",
      sale_price: "4500",
      price_range: null,
      currency_code: "KES",
      currency_symbol: "KSh",
      currency_minor_unit: 2,
      currency_decimal_separator: ".",
      currency_thousand_separator: ",",
      currency_prefix: "KSh ",
      currency_suffix: "",
    },
    price_html:
      '<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">KSh</span>&nbsp;45.00</span>',
    average_rating: "0",
    review_count: 0,
    images: [
      {
        id: 1894,
        src: "http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2.jpg",
        thumbnail:
          "http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2-300x300.jpg",
        srcset:
          "http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2.jpg 800w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2-300x300.jpg 300w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2-100x100.jpg 100w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2-150x150.jpg 150w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-zipper-2-768x768.jpg 768w",
        sizes: "(max-width: 800px) 100vw, 800px",
        name: "hoodie-with-zipper-2.jpg",
        alt: "",
      },
    ],
    categories: [
      {
        id: 213,
        name: "Hoodies",
        slug: "hoodies",
        link: "http://localhost/wordpress/product-category/clothing/hoodies/",
      },
    ],
    tags: [],
    attributes: [],
    variations: [],
    has_options: false,
    is_purchasable: true,
    is_in_stock: true,
    is_on_backorder: false,
    low_stock_remaining: null,
    sold_individually: false,
    add_to_cart: {
      text: "Add to cart",
      description: "Add &ldquo;Hoodie with Zipper&rdquo; to your cart",
      url: "?add-to-cart=1848",
      minimum: 1,
      maximum: 9999,
      multiple_of: 1,
    },
  },
  {
    id: 1847,
    name: "Hoodie with Pocket",
    parent: 0,
    type: "simple",
    variation: "",
    permalink: "http://localhost/wordpress/product/hoodie-with-pocket/",
    sku: "woo-hoodie-with-pocket",
    short_description: "<p>This is a simple product.</p>",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>",
    on_sale: true,
    prices: {
      price: "3500",
      regular_price: "4500",
      sale_price: "3500",
      price_range: null,
      currency_code: "KES",
      currency_symbol: "KSh",
      currency_minor_unit: 2,
      currency_decimal_separator: ".",
      currency_thousand_separator: ",",
      currency_prefix: "KSh ",
      currency_suffix: "",
    },
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">KSh</span>&nbsp;45.00</span></del> <ins><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">KSh</span>&nbsp;35.00</span></ins>',
    average_rating: "0",
    review_count: 0,
    images: [
      {
        id: 1893,
        src: "http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2.jpg",
        thumbnail:
          "http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2-300x300.jpg",
        srcset:
          "http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2.jpg 801w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2-300x300.jpg 300w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2-100x100.jpg 100w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2-150x150.jpg 150w, http://localhost/wordpress/wp-content/uploads/2022/06/hoodie-with-pocket-2-768x768.jpg 768w",
        sizes: "(max-width: 801px) 100vw, 801px",
        name: "hoodie-with-pocket-2.jpg",
        alt: "",
      },
    ],
    categories: [
      {
        id: 213,
        name: "Hoodies",
        slug: "hoodies",
        link: "http://localhost/wordpress/product-category/clothing/hoodies/",
      },
    ],
    tags: [],
    attributes: [],
    variations: [],
    has_options: false,
    is_purchasable: true,
    is_in_stock: true,
    is_on_backorder: false,
    low_stock_remaining: null,
    sold_individually: false,
    add_to_cart: {
      text: "Add to cart",
      description: "Add &ldquo;Hoodie with Pocket&rdquo; to your cart",
      url: "?add-to-cart=1847",
      minimum: 1,
      maximum: 9999,
      multiple_of: 1,
    },
  },
  {
    id: 1846,
    name: "Sunglasses",
    parent: 0,
    type: "simple",
    variation: "",
    permalink: "http://localhost/wordpress/product/sunglasses/",
    sku: "woo-sunglasses",
    short_description: "<p>This is a simple product.</p>",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>",
    on_sale: false,
    prices: {
      price: "9000",
      regular_price: "9000",
      sale_price: "9000",
      price_range: null,
      currency_code: "KES",
      currency_symbol: "KSh",
      currency_minor_unit: 2,
      currency_decimal_separator: ".",
      currency_thousand_separator: ",",
      currency_prefix: "KSh ",
      currency_suffix: "",
    },
    price_html:
      '<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">KSh</span>&nbsp;90.00</span>',
    average_rating: "0",
    review_count: 0,
    images: [
      {
        id: 1892,
        src: "http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2.jpg",
        thumbnail:
          "http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2-300x300.jpg",
        srcset:
          "http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2.jpg 801w, http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2-300x300.jpg 300w, http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2-100x100.jpg 100w, http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2-150x150.jpg 150w, http://localhost/wordpress/wp-content/uploads/2022/06/sunglasses-2-768x768.jpg 768w",
        sizes: "(max-width: 801px) 100vw, 801px",
        name: "sunglasses-2.jpg",
        alt: "",
      },
    ],
    categories: [
      {
        id: 214,
        name: "Accessories",
        slug: "accessories",
        link: "http://localhost/wordpress/product-category/clothing/accessories/",
      },
    ],
    tags: [],
    attributes: [],
    variations: [],
    has_options: false,
    is_purchasable: true,
    is_in_stock: true,
    is_on_backorder: false,
    low_stock_remaining: null,
    sold_individually: false,
    add_to_cart: {
      text: "Add to cart",
      description: "Add &ldquo;Sunglasses&rdquo; to your cart",
      url: "?add-to-cart=1846",
      minimum: 1,
      maximum: 9999,
      multiple_of: 1,
    },
  },
];

